name 'liquidprompt'
maintainer 'Kamil Forys'
maintainer_email 'kamil.forys@gmail.com'
license 'GPL v3'
description 'Installs/Configures liquidprompt'
long_description 'Installs/Configures liquidprompt'
version '0.2.0'
